# Generated by Django 4.2.4 on 2023-10-08 00:38

from django.db import migrations
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date_time',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
    ]
