# Generated by Django 4.2.4 on 2023-10-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cart_order_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
