# Generated by Django 4.2.4 on 2023-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cart_size_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity_based_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
