# Generated by Django 4.2.4 on 2023-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cart_quantity_based_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity_based_price',
            field=models.PositiveIntegerField(),
        ),
    ]
